container:
  image: python:3.7-buster
  cpu: 8
  memory: 24
env:
  DEBIAN_FRONTEND: noninteractive
  DIR: ${CIRRUS_WORKING_DIR}
  CC: clang
  

intialize_task:
  timeout_in: 120m
  
  dependecies_install_script:
    - apt-get update
    - apt-get install -y autoconf clang cmake curl git libbsd-dev libblocksruntime-dev libcurl4-openssl-dev libedit-dev libicu-dev icu-devtools libpython-dev libncurses5-dev libsqlite3-dev libxml2-dev libxml2 ninja-build pkg-config systemtap-sdt-dev rsync sqlite3 swig tzdata unzip uuid-dev
  
  check_versions_script:
    - clang --version
   
  get_sources_script:
    - wget https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel-3.1.0-installer-linux-x86_64.sh
    - chmod +x bazel-*.sh
    - ./bazel-3.1.0-installer-linux-x86_64.sh
    - git clone -q --depth 1 --single-branch https://github.com/tensorflow/tensorflow tensorflow
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python get-pip.py
  
  configure_script:
#     - export PATH= :$PATH
    - pip install --upgrade astunparse numpy PyYAML gast h5py six grpcio portpicker scipy scikit-learn attrs wrapt
    - pip install keras_preprocessing==1.1.0 --no-deps
    - yes '' | ./configure || true
  
  bazel_build_script:
    - cd $DIR/tensorflow
    - bazel build -c opt --config=monolithic --config=v2 --config=noaws --config=nogcp --config=nohdfs --config=nonccl --verbose_failures  //tensorflow:tensorflow_cc //tensorflow:install_headers

  tensorflow_cc_artifacts:
    path: $DIR/tensorflow/bazel-bin
