container:
  image: python:3.7-buster
  cpu: 8
  memory: 24
env:
  DEBIAN_FRONTEND: noninteractive
  DIR: ${CIRRUS_WORKING_DIR}
  CC: clang
  

intialize_task:
  timeout_in: 120m
  
  dependecies_install_script:
    - apt-get update
    - apt-get install -y autoconf clang cmake curl git zip
  
  check_versions_script:
    - clang --version
   
  get_sources_script:
    - wget https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel-3.1.0-installer-linux-x86_64.sh
    - chmod +x bazel-*.sh
    - ./bazel-3.1.0-installer-linux-x86_64.sh
    - git clone -q --depth 1 --single-branch https://github.com/tensorflow/tensorflow tensorflow
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python get-pip.py
  
  configure_script:
#     - export PATH= :$PATH
    - cd $DIR/tensorflow
    - pip install --upgrade astunparse numpy PyYAML gast h5py six grpcio portpicker scipy scikit-learn attrs wrapt
    - pip install keras_preprocessing==1.1.0 --no-deps
    - yes '' | ./configure || true
  
  # added for building debug version - https://stackoverflow.com/a/53239413
  # https://github.com/tensorflow/tensorflow/issues/27744
  # enable cache by appending --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
  # if used --config=monolithic for generating libtensorflow_cc.so then tensorflow_framework
  # is not required. only tensorflow_cc.so will work.
  bazel_build_script:
    - cd $DIR/tensorflow
    - bazel build -c opt --config=v2 --config=noaws --config=nogcp --config=nohdfs --config=nonccl --verbose_failures  //tensorflow:tensorflow_cc --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
    - bazel build --cxxopt="-g" --cxxopt="-O1" --config=v2 --config=noaws --config=nogcp --config=nohdfs --config=nonccl --verbose_failures  //tensorflow:tensorflow_framework --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
    - bazel build -c opt --config=v2 --config=noaws --config=nogcp --config=nohdfs --config=nonccl --verbose_failures  //tensorflow:install_headers
#     - ls -l bazel-bin/
    - cd bazel-bin/tensorflow/ && zip -r $DIR/tensorflow_include_cpp.zip include/
#     - cp bazel-bin/tensorflow/libtensorflow_framework.so.* $DIR/artifacts/libtensorflow_framework/
#     - cp bazel-bin/tensorflow/libtensorflow_cc.so.* $DIR/libtensorflow_cc/
   
  libtensorflow_artifacts:
    path: tensorflow/bazel-bin/tensorflow/*.so.*
   
  tensorflow_inlcude_artifacts:
    path: tensorflow_include_cpp.zip
