container:
  image: python:3.7-buster
  cpu: 8
  memory: 24
env:
  DEBIAN_FRONTEND: noninteractive
  DIR: ${CIRRUS_WORKING_DIR}
  TF_ENABLE_XLA: 0
  VERSION: 2.1.1
  BRANCH_VERSION: r2.1
  CONCURRENT_THREADS: 16
  

intialize_task:
  timeout_in: 120m
  
  dependecies_install_script:
    - apt-get update
    - apt-get install -y build-essential curl git zip
  
  check_versions_script:
    - gcc --version
   
  get_sources_script:
    - wget https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel-0.29.1-installer-linux-x86_64.sh
    - chmod +x bazel-*.sh
    - ./bazel-0.29.1-installer-linux-x86_64.sh
    - git clone -q --depth 1 -b $BRANCH_VERSION --single-branch https://github.com/tensorflow/tensorflow tensorflow
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python get-pip.py
  
  configure_script:
    - cd $DIR/tensorflow
    - pip install --upgrade astunparse numpy PyYAML gast h5py six grpcio portpicker scipy scikit-learn attrs wrapt
    - pip install keras_preprocessing==1.1.0 --no-deps
    - yes '' | ./configure || true
  
  # added for building debug version - https://stackoverflow.com/a/53239413
  # https://github.com/tensorflow/tensorflow/issues/27744
  # enable cache by appending --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
  # if used --config=monolithic for generating libtensorflow_cc.so then tensorflow_framework is not required. only tensorflow_cc.so will work. 
  # see - https://github.com/tensorflow/tensorflow/blob/ed60f21980a1b9ebd85d4913a731c8b05b843cea/.bazelrc#L31
  # check this for build debug error https://github.com/tensorflow/tensorflow/issues/35623
  # remove --config=nogcp for v2.0.0 ......... https://github.com/tensorflow/tensorflow/issues/34878
  bazel_build_script:
    - cd $DIR/tensorflow
    - bazel build -j $CONCURRENT_THREADS --cxxopt="-Og" -c dbg --strip=never --config=v2 --config=noaws --config=nogcp --config=nohdfs --config=nonccl --verbose_failures  //tensorflow:tensorflow_cc //tensorflow:tensorflow_framework //tensorflow:install_headers --noincompatible_do_not_split_linking_cmdline --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
    - cd bazel-bin/tensorflow/ && zip -r $DIR/tensorflow_cpp.zip include/ 
    - cp libtensorflow_cc.so.$VERSION $DIR/ 
    - cp libtensorflow_framework.so.$VERSION $DIR/
  
  tensorflow_cc_artifacts:
    path: libtensorflow_cc.so.$VERSION
  
  tensorflow_framework_artifacts:
    path: libtensorflow_framework.so.$VERSION

  tensorflow_cpp_artifacts:
    path: tensorflow_cpp.zip
